name: default

kind: pipeline

steps:
  - name: build-and-push
    image: plugins/docker
    settings:
      username:
        from_secret: dockerhub_username
      password:
        from_secret: dockerhub_password
      repo: boro/squid-proxy
      tags:
        - latest
      cache_from:
        - "boro/squid-proxy:latest"

volumes:
  - name: dockersock
    host:
      path: /var/run/docker.sock
