name: default

kind: pipeline

steps:
  - name: build-latest
    image: plugins/docker
    settings:
      username:
        from_secret: dockerhub_username
      password:
        from_secret: dockerhub_password
      repo: boro/squid-proxy
      tags:
        - "latest"
    when:
      branch:
        - master

  - name: build-branch
    image: plugins/docker
    settings:
      username:
        from_secret: dockerhub_username
      password:
        from_secret: dockerhub_password
      repo: boro/squid-proxy
      tags:
        - "${DRONE_BRANCH}"
    when:
      branch:
        exclude:
          - master

volumes:
  - name: dockersock
    host:
      path: /var/run/docker.sock
